Repository vergecurrency/VERGE, pull requests merged in 2019-10, with the labels that each got.

#904 [VIP-1] Additional subsidy halvings v5
  src/chainparams.cpp
  src/test/main_tests.cpp
  src/validation.cpp
Labels: brainstorming, fork, p2p

#991 Update branding
  readme-header.png
  share/pixmaps/nsis-header.bmp
  share/pixmaps/nsis-wizard.bmp
  share/pixmaps/verge.ico
  share/pixmaps/verge128.png
  share/pixmaps/verge16.png
  share/pixmaps/verge256.png
  share/pixmaps/verge32.png
  share/pixmaps/verge64.png
  src/qt/res/icons/VERGE.icns
  src/qt/res/icons/VolumeIcon.icns
  src/qt/res/icons/about.png
  src/qt/res/icons/splash1.png
  src/qt/res/icons/verge.ico
  src/qt/res/icons/verge.png
  src/qt/res/icons/verge_testnet.ico
  src/qt/res/icons/verge_testnet.png
Labels: cosmetic issue

#992 Add coverage reports to circleci
  .circleci/config.yml
Labels: building-system, testing
