Repository vergecurrency/VERGE, pull requests merged in 2019-08, with the labels that each got.

#957 Fix fork v4 checks
  src/blockencodings.cpp
  src/blockencodings.h
  src/miner.cpp
  src/rpc/blockchain.cpp
  src/validation.cpp
  src/validation.h
Labels: bug, p2p, testing

#964 Add DNS seeds with dynamic peer lists which will resolve in verge hosts
  src/chainparams.cpp
Labels: enhancement, p2p

#965 Mining availability for certain algorithm
  src/rpc/mining.cpp
  src/validation.cpp
  src/validation.h
Labels: enhancement, mining

#967 update qt splash image
  src/qt/res/icons/splash1.png
Labels: cosmetic issue

#972 Transaction timing for block creation
  src/core_write.cpp
  src/miner.cpp
  src/miner.h
  src/rpc/rawtransaction.cpp
  src/validation.cpp
Labels: bug
